development:
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  database: demo_app_development
  password: admin

test:
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  database: demo_app_test
  password: admin

production:
  adapter: postgresql
  host: 127.0.0.1
  username: postgres
  database: demo_app_production
  password: admin